export const LANGUAGES = Object.freeze([
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
]);

export const CATEGORIES = Object.freeze([
  'Culture',
  'Stories',
  'Mindfulness',
  'Technology',
  'Creativity',
  'Life',
]);
export const MOODS = Object.freeze(['Curious', 'Unwind', 'Inspired']);
export const ARTWORKS = Object.freeze(['orbit', 'sunrise', 'botanical', 'waves', 'city', 'bloom']);

const ideas = [
  [
    'quiet-hours-01',
    'The art of slowing down',
    'The Quiet Hours',
    'Quiet Hours studio',
    'An imagined conversation about making room for ordinary moments, gentle rituals, and a slower morning.',
    'en',
    'Mindfulness',
    'Unwind',
    'orbit',
  ],
  [
    'small-wonders-01',
    'A city that listens',
    'Small Wonders',
    'Small Wonders studio',
    'A fictional walk through the sounds, shared spaces, and unexpected kindness of a city after rain.',
    'en',
    'Culture',
    'Curious',
    'city',
  ],
  [
    'bright-margins-01',
    'Begin before you are ready',
    'Bright Margins',
    'Bright Margins studio',
    'An editorial idea about playful first drafts, creative courage, and the pleasure of trying something new.',
    'en',
    'Creativity',
    'Inspired',
    'bloom',
  ],
  [
    'human-circuit-01',
    'Technology with a little more soul',
    'The Human Circuit',
    'Human Circuit studio',
    'A fictional episode concept exploring humane technology, thoughtful tools, and the people behind them.',
    'en',
    'Technology',
    'Curious',
    'waves',
  ],
  [
    'nidhana-01',
    'ನಿಧಾನವಾಗಿ ಒಂದು ಹೆಜ್ಜೆ',
    'ನಿಧಾನ · Nidhana',
    'Nidhana studio',
    'One slow step: an imagined Kannada reflection on a quieter day and noticing the world around us.',
    'kn',
    'Mindfulness',
    'Unwind',
    'botanical',
  ],
  [
    'oorina-kathe-01',
    'ಮಳೆಯ ನಂತರದ ಊರು',
    'ಊರಿನ ಕಥೆ · Oorina Kathe',
    'Oorina Kathe studio',
    'The town after rain: a fictional Kannada story idea about familiar streets, small shops, and belonging.',
    'kn',
    'Stories',
    'Curious',
    'city',
  ],
  [
    'hosa-belaku-01',
    'ಹೊಸ ಬೆಳಕಿನ ಹುಡುಕಾಟ',
    'ಹೊಸ ಬೆಳಕು · Hosa Belaku',
    'Hosa Belaku studio',
    'In search of new light: a Kannada editorial concept about craft, experimentation, and finding your own creative voice.',
    'kn',
    'Creativity',
    'Inspired',
    'sunrise',
  ],
  [
    'namma-nudi-01',
    'ನಮ್ಮ ಮಾತಿನ ಮಧುರತೆ',
    'ನಮ್ಮ ನುಡಿ · Namma Nudi',
    'Namma Nudi studio',
    'The warmth of our words: a fictional Kannada episode about everyday language, local culture, and stories passed between generations.',
    'kn',
    'Culture',
    'Curious',
    'bloom',
  ],
  [
    'thoda-thehraav-01',
    'थोड़ा ठहर कर',
    'थोड़ा ठहराव · Thoda Thehraav',
    'Thehraav studio',
    'Pause for a moment: an imagined Hindi reflection on rest, breathing room, and finding ease in daily life.',
    'hi',
    'Mindfulness',
    'Unwind',
    'waves',
  ],
  [
    'galiyon-ke-kisse-01',
    'गलियों में छुपी कहानियाँ',
    'गलियों के किस्से · Galiyon Ke Kisse',
    'Galiyon studio',
    'Stories hidden in the lanes: a fictional Hindi episode concept about neighbourhood memories and unexpected connections.',
    'hi',
    'Stories',
    'Curious',
    'city',
  ],
  [
    'nayi-subah-01',
    'एक नई शुरुआत',
    'नई सुबह · Nayi Subah',
    'Nayi Subah studio',
    'A new beginning: a Hindi editorial idea about small changes, everyday courage, and a fresh perspective on life.',
    'hi',
    'Life',
    'Inspired',
    'sunrise',
  ],
  [
    'kal-ki-soch-01',
    'कल की दुनिया, आज के सवाल',
    'कल की सोच · Kal Ki Soch',
    'Kal Ki Soch studio',
    'Tomorrow’s world, today’s questions: an imagined Hindi exploration of useful technology and the choices that shape it.',
    'hi',
    'Technology',
    'Curious',
    'orbit',
  ],
];

export const SEED_EPISODES = Object.freeze(
  ideas.map((entry, index) => {
    const [id, title, show, host, description, language, category, mood, artwork] = entry;
    return Object.freeze({
      id,
      title,
      show,
      host,
      description: `${description} Fictional editorial demo; the audio is an original 30-second ambient preview, not spoken dialogue.`,
      language,
      category,
      mood,
      artwork,
      duration: 30,
      audioUrl: '/media/audiora-preview.mp3',
      publishedAt: new Date(Date.UTC(2026, 8, 30 - index)).toISOString(),
      featured: index === 0,
      demo: true,
    });
  }),
);
